name: Build LaTeX document

on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
             document1/main1.tex
             document2/main2.tex

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Github Actions
          message: 'Add pdf'
